### ISSUE TITLE
Height in Landscape

### ISSUE THREAD

**Issue by J-Jamet** [enricocid/Color-picker-library#5]
Height in Landscape isn't good at all for many screen sizes and resolutions.
![device-2017-02-20-014803](https://cloud.githubusercontent.com/assets/19224038/23108540/12f7c5f0-f70f-11e6-898a-c75d39de8ed7.png)
(Otherwise it is a good app, I will be inspired by some features for my API)

**Comment by enricocid** [comment]
Color picker dialog is no longer mantainer but it has been replaced by ColorBox:
https://github.com/enricocid/ColorBox-library

ColorBox will be available within the next hours
