### ISSUE TITLE
Compilation not possible

### ISSUE THREAD

**Issue by ramack** [enricocid/Color-picker-library#6]
Not sure whether this is really an issue in the code or just me not understanding how to use it.
I added

```dependencies {
    ...
    compile 'com.github.enricocid:cpl:1.0.3'
}
```
in build.gradle and the dependency was downloaded. Nevertheless _colorDialog.ColorSelectedListener_ is not found and the _import com.enrico.colorpicker.colorDialog;_ is shown as not used in Android studio. And a build fails with
```
Error:(46, 14) The type EditActivity must implement the inherited abstract method colorDialog.ColorSelectedListener.onColorSelection(DialogFragment, int)
Error:(132, 17) The method onColorSelection(DialogFragment, int) of type EditActivity must override or implement a supertype method
```

Any idea?

**Comment by enricocid** [comment]
Did you add 

implements colorDialog.ColorSelectedListener

On your edit activity?

**Comment by ramack** [comment]
yes, I did. But android studio "painted" colorDialog.ColorSelectedListener in red... Somehow the library doesn't seem to be imported correctly.

**Comment by enricocid** [comment]
Ok. My account was deleted from bintray. You have to download the library and import yourself. See the example to see how to setup you're build.gradle

**Comment by ramack** [comment]
interesting, because it looked as if something was downloaded. - you might think of recreating the account. At the moment I got https://github.com/Pes8/android-material-color-picker-dialog working but maybe I try your component later, as I somehow like the direct color access via the palette.

**Comment by enricocid** [comment]
Color picker dialog is no longer mantainer but it has been replaced by ColorBox:
https://github.com/enricocid/ColorBox-library

ColorBox will be available within the next hours
